'use strict';
(()=>{
 const repository='https://github.com/ItzKuroYT/nivora-public';
 const icons={shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6ZM9 12l2 2 4-4',tabs:'M7 3h14v14M3 7h14v14H3z',sliders:'M5 3v5m0 4v9M12 3v10m0 4v4M19 3v2m0 4v12M2 8h6m1 9h6m1-12h6',book:'M3 4h6l3 2 3-2h6v16h-6l-3 2-3-2H3ZM12 6v16',cube:'m12 3 9 5v9l-9 5-9-5V8ZM3 8l9 5 9-5M12 13v9',windows:'M3 5l8-1v8H3ZM13 4l8-1v9h-8ZM3 14h8v7l-8-1ZM13 14h8v9l-8-1Z',mac:'M16 3c0 2-1 3-3 4 0-2 1-4 3-4ZM17 8c-2-1-3 0-5 0s-3-1-5 0C2 11 6 22 10 21l2-1 2 1c3 1 6-5 6-6-4-2-4-5-1-6Z',linux:'M9 5c0-4 6-4 6 0v3l3 7c2 5-14 5-12 0l3-7ZM10 6h.1M14 6h.1M10 10h4M5 20l-2 2h7m9-2 2 2h-7',ios:'M7 2h10v20H7zM11 19h2',android:'M5 9h14v10H5ZM7 9c0-7 10-7 10 0M8 2l1 3m7-3-1 3M3 10v7m18-7v7M8 19v3m8-3v3M9 7h.1M15 7h.1'};
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.tabs}"/></svg>`;
 function safeDownload(url){try{const parsed=new URL(url);return parsed.origin==='https://github.com'&&parsed.pathname.startsWith('/ItzKuroYT/nivora-public/releases/download/')&&!parsed.username&&!parsed.password?parsed.href:null;}catch{return null;}}
 function fromRelease(release,fallback){if(!release||release.draft||release.prerelease||!/^v\d+\.\d+\.\d+$/.test(release.tag_name)||!Array.isArray(release.assets))return fallback;const version=release.tag_name.slice(1),platforms=structuredClone(fallback.platforms);for(const [key,pattern] of Object.entries({windows:/^Nivora-Browser-Setup-[\d.]+\.exe$/,mac:/^Nivora-Browser-[\d.]+-universal\.dmg$/,linux:/^Nivora-Browser-[\d.]+-(?:x64|x86_64)\.AppImage$/})){const asset=release.assets.find(a=>pattern.test(a.name)&&safeDownload(a.browser_download_url));if(asset){platforms[key]={...platforms[key],status:'available',url:asset.browser_download_url,file:asset.name,bytes:asset.size,version,sha256:asset.digest?.startsWith('sha256:')?asset.digest.slice(7):'',format:key==='windows'?'Setup EXE':key==='mac'?'DMG · Intel & Apple silicon':'AppImage · x64'};}else{platforms[key]={...platforms[key],status:'planned',url:'',file:'',sha256:''};}}const portable=release.assets.find(a=>/^Nivora-Browser-Portable-[\d.]+\.exe$/.test(a.name)&&safeDownload(a.browser_download_url));platforms.windows.portableURL=portable?.browser_download_url||'';return {version,platforms};}
 function card(key,p){const available=p.status==='available'&&safeDownload(p.url);return `<article class="platform-card ${key==='windows'&&available?'featured':''}" id="${key}"><div class="platform-top"><span class="platform-icon">${icon(key)}</span><span class="availability ${available?'available':''}">${available?(key==='linux'?'Preview':'Available'):'Coming soon'}</span></div><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p>${available?`<a class="button ${key==='windows'?'primary':'secondary'}" href="${esc(p.url)}">Download ${esc(p.format)} <span aria-hidden="true">↓</span></a>`:`<a class="button planned" href="wiki.html#platforms">${key==='ios'||key==='android'?'Native app planned':'Desktop build pending'} <span aria-hidden="true">↗</span></a>`}<div class="platform-details"><span>${available?`v${esc(p.version||'')} · ${Math.round((p.bytes||0)/1048576)} MB`:'See platform details in the wiki'}</span>${available&&p.sha256?`<button data-copy-checksum="${esc(p.sha256)}" aria-label="Copy ${esc(p.name)} SHA-256 checksum">SHA-256</button>`:''}</div>${key==='windows'&&p.portableURL&&safeDownload(p.portableURL)?`<div class="platform-details"><a href="${esc(p.portableURL)}">Download portable EXE ↗</a></div>`:''}${available&&p.sha256?`<details class="platform-checksum"><summary>Show checksum</summary><p>${esc(p.sha256)}</p></details>`:''}</article>`;}
 async function boot(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));const menu=document.querySelector('.mobile-menu'),navigation=document.querySelector('#navigation');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));navigation.classList.toggle('open',open);});navigation?.addEventListener('click',event=>{if(event.target.closest('a')){navigation.classList.remove('open');menu?.setAttribute('aria-expanded','false');}});
  const search=document.querySelector('#wiki-search'),sections=[...document.querySelectorAll('[data-wiki-section]')];search?.addEventListener('input',()=>{const q=search.value.toLowerCase().trim();let found=0;for(const section of sections){const visible=section.textContent.toLowerCase().includes(q);section.hidden=!visible;if(visible)found++;const link=document.querySelector(`.wiki-nav a[href="#${section.id}"]`);if(link)link.hidden=!visible;}document.querySelector('#wiki-empty').hidden=found>0;});if(sections.length&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){document.querySelectorAll('.wiki-nav a').forEach(link=>link.classList.toggle('active',link.hash==='#'+entry.target.id));}},{rootMargin:'-10% 0px -75% 0px'});sections.forEach(section=>observer.observe(section));}
  if(!document.querySelector('#download-grid,[data-primary-download]'))return;let catalog;try{const response=await fetch('data/releases.json',{cache:'no-store'});if(!response.ok)throw Error('Catalog unavailable');catalog=await response.json();}catch{const grid=document.querySelector('#download-grid');if(grid)grid.innerHTML=`<div class="notice">The download catalog is unavailable. <a href="${repository}/releases/latest">Open official releases</a>.</div>`;return;}
  renderCatalog(catalog);try{const response=await fetch('https://api.github.com/repos/ItzKuroYT/nivora-public/releases/latest',{signal:AbortSignal.timeout(4000),headers:{Accept:'application/vnd.github+json'}});if(response.ok)renderCatalog(fromRelease(await response.json(),catalog));}catch{}
 }
 function renderCatalog(catalog){const grid=document.querySelector('#download-grid');if(grid)grid.innerHTML=Object.entries(catalog.platforms).map(([key,p])=>card(key,p)).join('');document.querySelectorAll('[data-release-label]').forEach(el=>el.textContent='Nivora '+catalog.version);const primary=document.querySelector('[data-primary-download]');const detected=/Mac/.test(navigator.platform)?'mac':/Linux/.test(navigator.platform)&&!/Android/.test(navigator.userAgent)?'linux':'windows';const p=catalog.platforms[detected];if(primary&&p.status==='available'&&safeDownload(p.url)){primary.href=p.url;primary.innerHTML='Download for '+esc(p.name)+' <span aria-hidden="true">↓</span>';document.querySelector('[data-download-caption]').textContent=p.format+' · No account needed to browse';}}
 function toast(message){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.remove(),3000);}
 if(typeof module!=='undefined')module.exports={safeDownload,fromRelease,card};if(typeof document!=='undefined'){document.addEventListener('click',async event=>{const button=event.target.closest('[data-copy-checksum]');if(button){try{await navigator.clipboard.writeText(button.dataset.copyChecksum);toast('SHA-256 checksum copied.');}catch{toast('Open Show checksum to copy it manually.');}}});boot();}
})();
